import type { CapturedRequest } from "../lib/har";

/** 확장 밖(vite dev)에서 UI 확인용 목 데이터 */
export function mockRequests(): CapturedRequest[] {
  const base = {
    startedAt: new Date().toISOString(),
    resourceType: "fetch",
    pageUrl: "https://www.example.com/mypage",
    requestHeaders: {
      authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
      "user-agent": navigator.userAgent,
      "content-type": "application/json",
      accept: "application/json",
    },
  };
  return [
    {
      ...base,
      id: "m1",
      method: "GET",
      url: "https://api.example.com/user/v4/profile",
      fullUrl: "https://api.example.com/user/v4/profile",
      query: {},
      status: 200,
      statusText: "OK",
      durationMs: 120,
      responseHeaders: { "content-type": "application/json", "x-request-id": "req-ok-1" },
      responseBody: { mimeType: "application/json", text: '{"id":1,"name":"sangzin"}' },
    },
    {
      ...base,
      id: "m2",
      method: "POST",
      url: "https://api.example.com/user/v4/withdrawal",
      fullUrl: "https://api.example.com/user/v4/withdrawal?force=true",
      query: { force: "true" },
      status: 500,
      statusText: "Internal Server Error",
      durationMs: 812,
      requestBody: { mimeType: "application/json", text: '{"userId":1,"reason":"bye"}' },
      responseHeaders: { "content-type": "application/json", "x-request-id": "req-err-2", "x-b3-traceid": "abc123" },
      responseBody: {
        mimeType: "application/json",
        text: '{"timestamp":"2026-09-07T11:05:22.293+09:00","status":500,"error":"Internal Server Error","path":"/user/v4/withdrawal"}',
      },
    },
    {
      ...base,
      id: "m3",
      method: "GET",
      url: "https://dev-api.example.com/order/v2/list",
      fullUrl: "https://dev-api.example.com/order/v2/list?page=1&size=20",
      query: { page: "1", size: "20" },
      status: 401,
      statusText: "Unauthorized",
      durationMs: 45,
      responseHeaders: { "content-type": "application/json" },
      responseBody: { mimeType: "application/json", text: '{"code":"AUTH_EXPIRED","message":"토큰이 만료되었습니다"}' },
    },
    {
      ...base,
      id: "m4",
      method: "POST",
      url: "https://api.example.com/payment/v1/confirm",
      fullUrl: "https://api.example.com/payment/v1/confirm",
      query: {},
      status: 0,
      statusText: "",
      errorReason: "net::ERR_FAILED",
      durationMs: 30012,
      requestBody: { mimeType: "application/json", text: '{"orderId":"O-1"}' },
      responseHeaders: {},
    },
    {
      ...base,
      id: "m5",
      resourceType: "image",
      method: "GET",
      url: "https://cdn.example.com/logo.png",
      fullUrl: "https://cdn.example.com/logo.png",
      query: {},
      status: 200,
      statusText: "OK",
      durationMs: 20,
      responseHeaders: { "content-type": "image/png" },
      responseBody: { mimeType: "image/png", text: "iVBORw0KGgo=", encoding: "base64" },
    },
  ];
}
